config/routes.rb
Rails.application.routes.draw do

  get 'claims/index'

  get 'claims/new'

  # PRIVATE PUB TESTS
  get '/pub' => 'home#pub'
  post '/msg' => 'home#msg'

  get 'paypal_accounts/new'

  get 'paypal_accounts/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/invites', to: 'invites#new', via: 'get'
  resources :invites, only: [:new, :create]

  resources :requested_items
  resources :billings
  # match '/billings/charge' => 'billings#charge', via: 'patch'
  put '/reservations/:id/updateWithPay' => 'reservations#updateWithPay'
  put '/reservations/:id/updateCheck' => 'reservations#updateCheck'
  put '/approveItem' => 'items#approveItem'

  get '/checkStripe' => 'items#check_stripe_connect'
  get '/charge' => 'billings#charge'
  get 'reviews/new'
  get 'reviews/show'
  get 'reviews/index'

  get 'dashboard/index'

  # post "emailapi/subscribe" => 'emailapi#subscribe'

  # get '/about' => 'pages#about'
  # get '/faq' => 'pages#faq'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/conversations/:conversation_id/messages' => 'messages#show', as: :message
  post '/conversations/messages/new' => 'messages#new_message'
  post '/conversations/read' => 'conversations#read'

  post '/newclaim' => 'reservations#newclaim'

  resources :conversations, except: :show
  resources :activities
  # resources :profiles

  match "/contacts/:importer/callback" => "invites#new", :via => [:get]
  # google contacts callback
  match "/oauth2callback" => "main#contact", :via => [:get]
  # Yahoo contacts callback
  match "/callback" => "main#contact", :via => [:get]

  match "/send-invites" => "main#invite", :via => [:get]
  match "/import-emails" => 'invites#new', :via => [:get]

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  post '/items/share' => 'items#share'
  get '/items/item_preview/:id' => 'items#item_preview', as: :shareItem

  # get 'tags/index'
  resources :items do
    resources :reviews, only: [:create, :destroy]
  end
  resources :search_suggestions
  resources :password_resets,   only: [:new, :create, :edit, :update]
  resources :relationships,     only: [:create, :destroy]

  resources :item_attachments
  match '/item_attachments_delete' =>'item_attachments#destroy_img', :via => [:destroy]


  resources :items do
    resources :reservations, only: [:create, :update]
  end

  get '/preloadDates' => 'items#preloadDates'
  # get '/preload' => 'reservations#preload'

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  resources :reservations, only: [:index]

  resources :users, only: [:new, :create, :show] do
    collection do
      get   :edit
      patch :update
    end
    member do
      get :confirm_email
      get :following, :followers
    end
  end

  match '/auth/stripe_connect' =>'stripe_omniauth_callbacks#passthru', :via => [:get, :post]
  match '//auth/stripe_connect/callback' =>'stripe_omniauth_callbacks#stripe_connect', :via => [:get, :post]

  post '/users/create_email/' => 'users#create_email'
  get '/users/create_email/edit' => 'users#edit'
  patch '/users/create_email/' => 'users#update_email'
  patch '/users/code_update/' => 'users#code_update'
  put '/about_me_edit/' => 'users#update'
  # get 	'/message'  => 'users#message'
  # patch '/users/create_email' => 'users#create_email', :as => 'users/create_email'

  match '/tags/index' => 'tags#index', :via => :get
  # match '/tags/:id' => 'tags#show', :via => :get
  get 'tags/:tagname' => 'tags#tagged_items', as: :tagged_items
  get 'tags/:tag', to: "tags#index", as: "tag"

  match 'sessions/create_email' => 'sessions#create_email', :via => :post

  # match 'sessions/create_email' => 'sessions#create_email', :via => :post

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  # get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'pages#landing_main'
  get '/home' => 'home#index', as: "home", via: [:get]




  #api
  # namespace :api do
  #   namespace :v1 do
  #     resources :users, only: [:index, :create, :show, :update, :destroy]
  #     resources :items, only: [:index, :create, :show, :update, :destroy]
  #     # resources :sessions, only: [:create]
  #     match '/sessions' => 'sessions#create', :via => :get
  #
  #     get '/login' => 'users#login'
  #   end
  # end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}"
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @items = Item.page(params[:page]).per(28).order('created_at DESC')
    @conversations = Conversation.received(current_user)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_items.html.erb
<!-- <div id="">
  <%# @user.items.each do |p| %>
    <%#= render "items/index", {p: p} %>
  <%# end %>
</div> -->

app/views/dashboard/index.html.erb
<div class="container desktop">
    <div class="row">
		  <div class="col-sm-4 hidden-xs" style="margin-top: 7px;">
        <div class="card hovercard dashB">
            <div class="avatar">
                <% if is_provider? %>
                  <%= image_tag "//graph.facebook.com/#{current_user.uid}/picture?type=large" %>
                <% else %>
                  <!-- <img alt="" src="<%#= current_user.avatar || current_user.image %>"> -->
                  <img src="<%= current_user.image || current_user.avatar %>" alt="..." class="">
                <% end %>
            </div>
            <div class="info">
                <div style"padding-left: 3px;" class="title">
                    <!-- <a target="_blank" href="http://scripteden.com/"><%= current_user.name || current_user.first_name %></a> -->
                    <%= current_user.first_name.capitalize %>
                </div>
                <br>
                <div style="text-align: left;font-size: 20px;color: #dedede;" class="">
                  <i style="color:black;padding-left: 6px;padding-right: 5px;" class="fa fa-map-marker"></i> <%= current_user.location || 'n/a' %>
                </div>
                <br>
                <% @user ||= current_user %>
                <div style="text-align: left;font-size: 20px;color: #dedede;" class="stats">
                    <i style="color:black;padding-left: 3px;padding-right: 3px;" class="fa fa-user"></i> Following
                    <strong id="following" class="stat">
                      <%= @user.following.count %>
                    </strong>
               </div>
               <br>
               <div style="text-align: left;font-size: 20px;color: #dedede;" class="stats">
                    <i style="color:black;" class="fa fa-users"></i> Followers
                    <strong id="followers" class="stat">
                      <%= @user.followers.count %>
                    </strong>
                </div>
            </div>
            <!-- <section class="stats">
              <%#= render 'shared/stats' %>
            </section> -->
            <div class="bottom">
                <p><a class="btn btn-success btn-lg" href="<%= edit_users_path %>" role="button"><i class="fa fa-cog fa-lg"></i> Edit Profile</a></p>
            </div>
        </div>

      </div>
      <div class="col-xs-8 hidden-xs" style="margin-top: 17px;">

           <ul class="nav nav-pills dash-nav dash-nav-pointer">
              <li class="active"><a data-toggle="pill" href="#home">My Items</a></li>
              <li><a data-toggle="pill" href="#menu1">Following</a></li>
              <li><a data-toggle="pill" href="#menu2">Followers</a></li>
              <!-- <li><a data-toggle="pill" href="#menu3">Notifications</a></li> -->
          </ul>

          <div class="tab-content dash-content">
              <div id="home" class="tab-pane fade in active dash-pane">
                <!-- <h3>My Items</h3> -->
                <%= render partial: "items/index_items", locals: {user: @user, item: @item} %>
              </div>
              <div id="menu1" class="tab-pane fade dash-pane">
                  <!-- <h3>Following</h3> -->
                  <%= render partial: "users/show_following", locals: {user: @user} %>
              </div>
              <div id="menu2" class="tab-pane fade dash-pane">
                <!-- <h3>Followers</h3> -->
                <%= render partial: "users/show_followers", locals: {user: @user} %>
              </div>
              <!-- <div id="menu3" class="tab-pane fade dash-pane">
                <p>blahlalala</p>
              </div> -->
         </div>
      </div>
    </div>
</div>

<div class="container mobile">
    <div class="row">
    <div class="col-xs-12 text-center bhoechie-tab-container">
            <div class="list-group list-group-horizontal bhoechie-tab-menu">
                <a href="#" class="list-group-item active text-center">
                  <h4 class="glyphicon glyphicon-th-list"></h4><br/>My Items
                </a>
                <a href="#" class="list-group-item text-center">
                  <h4 class="glyphicon glyphicon-user"></h4><br/>Followers
                </a>
                <a href="#" class="list-group-item text-center">
                  <h4 class="glyphicon glyphicon-eye-open"></h4><br/>Following
                </a>
            </div>

            <div class="col-xs-12 bhoechie-tab">
                <!-- flight section -->
                <div class="bhoechie-tab-content active">
                    <center>
                      <%= render partial: "items/index_itemsMobile", locals: {user: @user, item: @item} %>
                    </center>
                </div>
                <!-- train section -->
                <div class="bhoechie-tab-content">
                    <center>
                      <%= render partial: "users/show_followers", locals: {user: @user} %>
                    </center>
                </div>

                <!-- hotel search -->
                <div class="bhoechie-tab-content">
                    <center>
                      <%= render partial: "users/show_following", locals: {user: @user} %>
                    </center>
                </div>
            </div>
        </div>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
  $("div.list-group>a").click(function(e) {
      e.preventDefault();
      $(this).siblings('a.active').removeClass("active");
      $(this).addClass("active");
      var index = $(this).index();
      $("div.bhoechie-tab>div.bhoechie-tab-content").removeClass("active");
      $("div.bhoechie-tab>div.bhoechie-tab-content").eq(index).addClass("active");
  });
});
</script>