config/routes.rb
Rails.application.routes.draw do

  get 'claims/index'

  get 'claims/new'

  # PRIVATE PUB TESTS
  get '/pub' => 'home#pub'
  post '/msg' => 'home#msg'

  get 'paypal_accounts/new'

  get 'paypal_accounts/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/invites', to: 'invites#new', via: 'get'
  resources :invites, only: [:new, :create]

  resources :requested_items
  resources :billings
  # match '/billings/charge' => 'billings#charge', via: 'patch'
  put '/reservations/:id/updateWithPay' => 'reservations#updateWithPay'
  put '/reservations/:id/updateCheck' => 'reservations#updateCheck'
  put '/approveItem' => 'items#approveItem'

  get '/checkStripe' => 'items#check_stripe_connect'
  get '/charge' => 'billings#charge'
  get 'reviews/new'
  get 'reviews/show'
  get 'reviews/index'

  get 'dashboard/index'

  # post "emailapi/subscribe" => 'emailapi#subscribe'

  # get '/about' => 'pages#about'
  # get '/faq' => 'pages#faq'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/conversations/:conversation_id/messages' => 'messages#show', as: :message
  post '/conversations/messages/new' => 'messages#new_message'
  post '/conversations/read' => 'conversations#read'

  post '/newclaim' => 'reservations#newclaim'

  resources :conversations, except: :show
  resources :activities
  # resources :profiles

  match "/contacts/:importer/callback" => "invites#new", :via => [:get]
  # google contacts callback
  match "/oauth2callback" => "main#contact", :via => [:get]
  # Yahoo contacts callback
  match "/callback" => "main#contact", :via => [:get]

  match "/send-invites" => "main#invite", :via => [:get]
  match "/import-emails" => 'invites#new', :via => [:get]

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  post '/items/share' => 'items#share'
  get '/items/item_preview/:id' => 'items#item_preview', as: :shareItem

  # get 'tags/index'
  resources :items do
    resources :reviews, only: [:create, :destroy]
  end
  resources :search_suggestions
  resources :password_resets,   only: [:new, :create, :edit, :update]
  resources :relationships,     only: [:create, :destroy]

  resources :item_attachments
  match '/item_attachments_delete' =>'item_attachments#destroy_img', :via => [:destroy]


  resources :items do
    resources :reservations, only: [:create, :update]
  end

  get '/preloadDates' => 'items#preloadDates'
  # get '/preload' => 'reservations#preload'

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  resources :reservations, only: [:index]

  resources :users, only: [:new, :create, :show] do
    collection do
      get   :edit
      patch :update
    end
    member do
      get :confirm_email
      get :following, :followers
    end
  end

  match '/auth/stripe_connect' =>'stripe_omniauth_callbacks#passthru', :via => [:get, :post]
  match '//auth/stripe_connect/callback' =>'stripe_omniauth_callbacks#stripe_connect', :via => [:get, :post]

  post '/users/create_email/' => 'users#create_email'
  get '/users/create_email/edit' => 'users#edit'
  patch '/users/create_email/' => 'users#update_email'
  patch '/users/code_update/' => 'users#code_update'
  put '/about_me_edit/' => 'users#update'
  # get 	'/message'  => 'users#message'
  # patch '/users/create_email' => 'users#create_email', :as => 'users/create_email'

  match '/tags/index' => 'tags#index', :via => :get
  # match '/tags/:id' => 'tags#show', :via => :get
  get 'tags/:tagname' => 'tags#tagged_items', as: :tagged_items
  get 'tags/:tag', to: "tags#index", as: "tag"

  match 'sessions/create_email' => 'sessions#create_email', :via => :post

  # match 'sessions/create_email' => 'sessions#create_email', :via => :post

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  # get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'pages#landing_main'
  get '/home' => 'home#index', as: "home", via: [:get]




  #api
  # namespace :api do
  #   namespace :v1 do
  #     resources :users, only: [:index, :create, :show, :update, :destroy]
  #     resources :items, only: [:index, :create, :show, :update, :destroy]
  #     # resources :sessions, only: [:create]
  #     match '/sessions' => 'sessions#create', :via => :get
  #
  #     get '/login' => 'users#login'
  #   end
  # end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}"
  end

end

app/models/conversation.rb
class Conversation < ActiveRecord::Base

  belongs_to :sender, :foreign_key => :sender_id, :class_name => 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, :class_name => 'User'

  has_many :messages, dependent: :destroy

  belongs_to :reservation
  accepts_nested_attributes_for :messages

  # validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end

  scope :sent, -> (user) { where('sender_id = ?', user) }
  scope :received, -> (user) { where('recipient_id = ?', user) }

  def message_time
    created_at.strftime("%l:%M %p - %B #{created_at.day.ordinalize}")
  end

  def sender?(user)
    sender == user
  end

  def recipient?(user)
    recipient == user
  end

  def partner(user)
    user == recipient ? sender : recipient
  end

  def unread_msgs?(user)
    messages.recipient(user).unread?.exists?
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :code_require!
  before_action :find_conversations
  def index
    @users = User.all
    @conversations = current_user.all_conversations
    @sent = Conversation.sent(current_user)
  end

  def create
    @conversation = Conversation.new(
      recipient_id: params[:rid].to_i,
      sender_id: params[:sid].to_i
    )
    if @conversation.save
      @message = @conversation.messages.create(
        body: params[:body],
        user_id: params[:sid].to_i
      )

      data = { body: params[:body], rid: params[:rid], sid: current_user.id, from: current_user.full_name.capitalize, cid: @conversation.id, avatar: current_user.img }
      MessageBus.publish "/conversations/from-#{current_user.id}", data
      MessageBus.publish "/conversations/to-#{params[:rid]}", data

      render json: { cid: @conversation.id }
    else
      render json: { error: 'error' }
    end
  end

  def read
    @conversation = Conversation.find(params[:cid].to_i)
    @conversation.messages.recipient(current_user).update_all(read: true)
    render json: { unread: current_user.unread_count }
  end

  def destroy
    @conversation = Conversation.find(params[:id])
    @conversation.messages.destroy
    @conversation.destroy
    redirect_to conversations_path
  end

  private

  def conversation_params
    params.require(:conversation).permit(:sender_id, :recipient_id, :reservation_id,
                messages_attributes: [:body, :user_id, :reservation_id, :read, :conversation_id] )
  end

  def find_conversations
    @conversations = Conversation.where('recipient_id = ? OR sender_id = ?', current_user, current_user)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def avatar(user)
    case user.provider
    when 'facebook'
      "//graph.facebook.com/#{user.uid}/picture?type=square"
    when 'google_oauth2'
      user.image
    else
      user.avatar.url
    end
  end

  def recipient_name(conversation)
    conversation.recipient.full_name || conversation.recipient.name
  end

  def sender_name(conversation)
    conversation.sender.full_name || conversation.sender.name
  end
end

app/views/conversations/_conversation.html.erb
<div class="row row-conv">
  <% if conversation.sender == current_user %>
    <div class="col-xs-12 col-sm-2">
      <a href="<%= message_path(conversation) %>" data-remote="true">
        <% if conversation.recipient.provider == "facebook" %>
          <%= image_tag "//graph.facebook.com/#{conversation.recipient.uid}/picture?type=square", class:"circle msgImg", 'data-cid' => conversation.id %>
        <% elsif conversation.recipient.provider == "google_oauth2" %>
          <img alt="" src="<%= conversation.recipient.image%>" style = "width: 80px; height:80px" class="circle msgImg" data-cid="<%= conversation.id %>">
        <% else %>
          <img alt="" src="<%= conversation.recipient.avatar%>" style = "width: 80px; height:80px" class="circle msgImg" data-cid="<%= conversation.id %>">
        <% end %>
      </a>
    </div>
    <div class="hidden-xs col-sm-10 col-conv" id="<%= "convo-#{conversation.id}" %>">
      <span class="name" style="min-width: 120px;">
        <strong><%= link_to recipient_name(conversation).capitalize,  message_path(conversation), remote: true, class: "name-conv", 'data-cid' => conversation.id %></strong>

        <div class="new-message-alert">
          <%= 'new' if conversation.unread_msgs?(current_user) %>
        </div> <br>
        <span class="badge"><%= conversation.message_time %></span>
        <span id="delete_conv">
          <%= link_to conversation_path(conversation), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fa fa-trash" aria-hidden="true"></i>
          <% end %>
        </span>
      </span> <br>
    </div>
 <% else %>
    <div class="col-xs-12 col-sm-2">
      <a href="<%= message_path(conversation) %>" data-remote="true">
        <% if conversation.sender.provider == "facebook" %>
          <%= image_tag "//graph.facebook.com/#{conversation.sender.uid}/picture?type=square", class:"circle msgImg", 'data-cid' => conversation.id %>
        <% elsif conversation.sender.provider == "google_oauth2" %>
          <img alt="" src="<%= conversation.sender.image%>" style = "width: 80px; height:80px" class="circle msgImg" data-cid="<%= conversation.id %>">
        <% else %>
          <img alt="" src="<%= conversation.sender.avatar%>" style = "width: 80px; height:80px" class="circle msgImg" data-cid="<%= conversation.id %>">
        <% end %>
      </a>
    </div>
    <div class="hidden-xs col-sm-10 col-conv" id="<%= "convo-#{conversation.id}" %>">
      <span class="name" style="min-width: 120px;">
        <strong><%= link_to sender_name(conversation).capitalize, message_path(conversation), remote: true, class: "name-conv", 'data-cid' => conversation.id %></strong>
        <div class="new-message-alert">
          <%= 'new' if conversation.unread_msgs?(current_user) %>
        </div>
        <br> <span class="badge"><%= conversation.message_time %></span>
      </span> <br>
    </div>
  <% end %>
</div>

app/views/conversations/_conversationMobile.html.erb
<div class="row row-conv">
  <% if conversation.sender == current_user %>
    <div class="col-md-2">
      <a href="<%= message_path(conversation) %>" data-remote="true">
        <% if conversation.recipient.provider == "facebook" %>
          <%= image_tag "//graph.facebook.com/#{conversation.recipient.uid}/picture?type=square", class:"circle msgImg" %>
        <% elsif conversation.recipient.provider == "google_oauth2" %>
          <img alt="" src="<%= conversation.recipient.image%>" style = "width: 80px; height:80px" class="circle">
        <% else %>
          <img alt="" src="<%= conversation.recipient.avatar%>" style = "width: 80px; height:80px" class="circle">
        <% end %>
      </a>
    </div>
    <div class="col-md-10 col-conv" id="<%= "convo-#{conversation.id}" %>">
      <span class="name" style="min-width: 120px;">
        <strong><%= link_to recipient_name(conversation).capitalize,  message_path(conversation), class: "name-conv", 'data-cid' => conversation.id %></strong>

        <div class="new-message-alert-mobile">
          <%= 'new' if conversation.unread_msgs?(current_user) %>
        </div> <br>
        <span class="badge"><%= conversation.message_time %></span>
      </span> <br>
    </div>
 <% else %>
    <div class="col-md-2">
      <a href="<%= message_path(conversation) %>" data-remote="true">
        <% if conversation.sender.provider == "facebook" %>
          <%= image_tag "//graph.facebook.com/#{conversation.sender.uid}/picture?type=square", class:"circle msgImg" %>
        <% elsif conversation.sender.provider == "google_oauth2" %>
          <img alt="" src="<%= conversation.sender.image%>" style = "width: 80px; height:80px" class="circle">
        <% else %>
          <img alt="" src="<%= conversation.sender.avatar%>" style = "width: 80px; height:80px" class="circle">
        <% end %>
      </a>
    </div>
    <div class="col-md-10 col-conv" id="<%= "convo-#{conversation.id}" %>">
      <span class="name" style="min-width: 120px;">
        <strong><%= link_to sender_name(conversation).capitalize, message_path(conversation), class: "name-conv", 'data-cid' => conversation.id %></strong>
        <div class="new-message-alert-mobile">
          <%= 'new' if conversation.unread_msgs?(current_user) %>
        </div>
        <br> <span class="badge"><%= conversation.message_time %></span>
      </span> <br>
    </div>
  <% end %>
</div>

app/views/conversations/index.html.erb
<!-- <div class="wrapper-main"> -->
<div class="container container-conv">
    <div class="row">
        <div class="col-xs-2 col-sm-5 col6-conv">
            <ul class="nav nav-tabs nav-conv">
                <li class="active">
                    <a href="#conversations" data-toggle="tab">Conversations</a>
                </li>
            </ul>
            <!-- Tab panes -->
            <div class="tab-content tab-conv">
                <div class="tab-pane fade in active" id="conversations">
                    <% if @conversations %>
                    <% @conversations.each do |conversation| %>
                    <%= render partial: 'conversation', locals: { conversation: conversation } %>
                    <% end %>
                    <% end %>
                </div>
            </div>
        </div>
        <div class="col-xs-10 col-md-7 msg-render"></div>
        <div class="hidden-form-conv"></div>
    </div>
</div>