config/routes.rb
Rails.application.routes.draw do

  get 'claims/index'

  get 'claims/new'

  # PRIVATE PUB TESTS
  get '/pub' => 'home#pub'
  post '/msg' => 'home#msg'

  get 'paypal_accounts/new'

  get 'paypal_accounts/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/invites', to: 'invites#new', via: 'get'
  resources :invites, only: [:new, :create]

  resources :requested_items
  resources :billings
  # match '/billings/charge' => 'billings#charge', via: 'patch'
  put '/reservations/:id/updateWithPay' => 'reservations#updateWithPay'
  put '/reservations/:id/updateCheck' => 'reservations#updateCheck'
  put '/approveItem' => 'items#approveItem'

  get '/checkStripe' => 'items#check_stripe_connect'
  get '/charge' => 'billings#charge'
  get 'reviews/new'
  get 'reviews/show'
  get 'reviews/index'

  get 'dashboard/index'

  # post "emailapi/subscribe" => 'emailapi#subscribe'

  # get '/about' => 'pages#about'
  # get '/faq' => 'pages#faq'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/conversations/:conversation_id/messages' => 'messages#show', as: :message
  post '/conversations/messages/new' => 'messages#new_message'
  post '/conversations/read' => 'conversations#read'

  post '/newclaim' => 'reservations#newclaim'

  resources :conversations, except: :show
  resources :activities
  # resources :profiles

  match "/contacts/:importer/callback" => "invites#new", :via => [:get]
  # google contacts callback
  match "/oauth2callback" => "main#contact", :via => [:get]
  # Yahoo contacts callback
  match "/callback" => "main#contact", :via => [:get]

  match "/send-invites" => "main#invite", :via => [:get]
  match "/import-emails" => 'invites#new', :via => [:get]

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  post '/items/share' => 'items#share'
  get '/items/item_preview/:id' => 'items#item_preview', as: :shareItem

  # get 'tags/index'
  resources :items do
    resources :reviews, only: [:create, :destroy]
  end
  resources :search_suggestions
  resources :password_resets,   only: [:new, :create, :edit, :update]
  resources :relationships,     only: [:create, :destroy]

  resources :item_attachments
  match '/item_attachments_delete' =>'item_attachments#destroy_img', :via => [:destroy]


  resources :items do
    resources :reservations, only: [:create, :update]
  end

  get '/preloadDates' => 'items#preloadDates'
  # get '/preload' => 'reservations#preload'

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  resources :reservations, only: [:index]

  resources :users, only: [:new, :create, :show] do
    collection do
      get   :edit
      patch :update
    end
    member do
      get :confirm_email
      get :following, :followers
    end
  end

  match '/auth/stripe_connect' =>'stripe_omniauth_callbacks#passthru', :via => [:get, :post]
  match '//auth/stripe_connect/callback' =>'stripe_omniauth_callbacks#stripe_connect', :via => [:get, :post]

  post '/users/create_email/' => 'users#create_email'
  get '/users/create_email/edit' => 'users#edit'
  patch '/users/create_email/' => 'users#update_email'
  patch '/users/code_update/' => 'users#code_update'
  put '/about_me_edit/' => 'users#update'
  # get 	'/message'  => 'users#message'
  # patch '/users/create_email' => 'users#create_email', :as => 'users/create_email'

  match '/tags/index' => 'tags#index', :via => :get
  # match '/tags/:id' => 'tags#show', :via => :get
  get 'tags/:tagname' => 'tags#tagged_items', as: :tagged_items
  get 'tags/:tag', to: "tags#index", as: "tag"

  match 'sessions/create_email' => 'sessions#create_email', :via => :post

  # match 'sessions/create_email' => 'sessions#create_email', :via => :post

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  # get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'pages#landing_main'
  get '/home' => 'home#index', as: "home", via: [:get]




  #api
  # namespace :api do
  #   namespace :v1 do
  #     resources :users, only: [:index, :create, :show, :update, :destroy]
  #     resources :items, only: [:index, :create, :show, :update, :destroy]
  #     # resources :sessions, only: [:create]
  #     match '/sessions' => 'sessions#create', :via => :get
  #
  #     get '/login' => 'users#login'
  #   end
  # end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_filter :authenticate_user!, only: :index
  before_filter :code_require!, only: :index

  def index
    @items = current_user.items.order(created_at: :desc)
    @pending = current_user.reservations.pending.order(created_at: :desc)
    @allItems = Item.all
    @feedItems = Item.all.where(approved: true).order(created_at: :desc)
  end

  def pub
    @conversation = Conversation.last
    @message = @conversation.messages.build
  end

  def msg
    MessageBus.publish '/private/'+ params[:rid], {msg: params[:msg], rid: params[:rid], from: current_user.name}
    render json: {status: 'yay'}
  end

  def authorize
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def tags(item)
    if item.tags
      item_tags = item.tags.pluck(:name).map do |tag| 
        link_to "##{tag}", tagged_items_path(tagname: tag)
      end
      item_tags.join(', ').html_safe
    end
  end

  def tag_cloud(item)
    if item.tags
      item_tags = item.tags.pluck(:name).map do |tag| 
        link_to "#{tag}", tagged_items_path(tagname: tag)
      end
      item_tags.join(' ').html_safe
    end
  end

  def format_date(date)
    date.strftime('%B %d, %Y')
  end
end

app/views/home/authorize.html.erb
<script type="text/javascript">
  top.location.href="https://sharecity.net/auth/facebook";
</script>

<!-- top.location.href="http://localhost:3000/auth/facebook"; -->

app/views/home/index.html.erb
<section id="home-page-section">
  <div class="container">
    <div class="row intro-header2">
      <div class="col-xs-12">
        <h3 style="color: #676767;">What are you looking for?</h3>
        <br>
        <div class="container-1">
          <span class="icon"><i class="fa fa-search"></i></span>
          <%= form_tag(items_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "#Search for items" %>
          <%#= submit_tag "Search" %>
          <% end %>
        </div>
      </div>
      <div class="col-xs-12 btnsMain mobile">
        <a class="semi-transparent-button with-border" id="btn1" href="#">Accepted Reservations</a>

        <a class="semi-transparent-button with-border" id="btn2" href="#">Request Pending</a>

        <a class="semi-transparent-button with-border" id="btn3" href="#">Request Received</a>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-6 feedMobile">
        <div class="twt-wrapper">
          <div class="panel feed">
            <div class="panel-heading about-bk-color">
              Feed
            </div>
            <div class="panel-body about-size" id="item-post-feed">
              <% @feedItems.each do |item| %>
              <%# if current_user.following?(item.user) || item.shared? %>
              <div class="feed-item">
                <div class="row">
                  <div class="col-xs-3 col-sm-2">
                    <% if item.item_attachments.present? %>
                    <%= image_tag item.item_attachments.first.image_url, class: "feIm" %>
                    <% else %>
                    <%= image_tag "missing", class: "feIm" %>
                    <% end %>
                  </div>
                  <div class="col-xs-9 col-sm-10">
                    <div class="row">
                      <div class="col-xs-8">
                        <span class="item-name"><%= link_to "#{item.name}", item_path(item) %></span>
                      </div>
                      <div class="col-xs-4 bookDiv">
                        <% if item.user != current_user %>
                        <span class="book-item">
                          <%= link_to 'Request', item_path(item) %>
                        </span>
                        <% end %>
                      </div>
                    </div>
                    <%= item.desc[0..14] + "..." %><br/>
                    <div class="">
                      <%= tags(item) %>
                    </div>
                    <div class="">
                      <strong>Owner:</strong> <%= link_to "#{username(item.user)[0..5]}", user_path(item.user) %>
                    </div>
                  </div>
                </div>
                <div class="row rowInfo">
                  <div class="col-xs-5">
                    <strong>Price:</strong> <%= pricetag(item) %>
                  </div>
                  <div class="col-xs-7">
                    <strong>Postal code:</strong> <%= item.postal_code %>
                  </div>
                  <!-- <div class="col-xs-4">
                    <strong>Owner:</strong> <%= link_to "#{username(item.user)[0..5]}", user_path(item.user) %>
                  </div> -->
                </div>
              </div>
              <%# end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 desktop hideForPe hideForRe" id="requestedFeed">
        <div class="twt-wrapper">
          <div class="panel feed">
            <div class="panel-heading about-bk-color">
              Accepted Reservations
            </div>
            <div class="panel-body" id="accepted-reservations">
              <%= render 'items/accepted_reservations' %>
              <%= render 'items/confirming' %>
              <%# Reservation.pending.each do |res| %>
              <!-- <div class="feed-item"> -->
              <%# unless res.user == current_user %>
              <!-- <strong><%#= link_to username(res.user).capitalize, user_path(res.user) %></strong> requested an <strong><%#= link_to "Item", item_path(res.item) %></strong> -->
              <!-- from <%#= link_to res.item.user.first_name, user_path(res.item.user) %> -->
              <!-- for <%#= res.start_date.strftime('%B %d') %> to <%#= format_date(res.end_date) %> -->
              <!-- <div class="accept-res"> -->
              <%#= link_to 'Contact', conversations_path(current_user, res.user), method: 'POST' %>
              <!-- </div> -->
              <%# end %>
              <!-- </div> -->
              <%# end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-6 desktop hideForFe hideForRe" id="requestedPending">
        <div class="twt-wrapper ">
          <div class="panel requested">
            <div class="panel-heading about-bk-color">
              Request Pending
            </div>
            <div class="panel-body" id="your-requests">
              <%= render 'items/pending' %>
              <%# if @pending.any? %>
              <%# @pending.each do |res| %>
              <!-- <div class="feed-item">
              You requested <strong><%#= link_to res.item.name, item_path(res.item) %></strong> from <%#= link_to res.item.user.full_name, user_path(res.item.user) %>
            </div> -->
            <%# end %>
            <%# end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 desktop hideForFe hideForPe" id="requestedReceived">
      <div class="twt-wrapper">
        <div class="panel requested">
          <div class="panel-heading about-bk-color">
            Request Received
          </div>
          <div class="panel-body" id="received-requests">
            <%= render 'items/request_received' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</section>
<!-- </div> -->



<!-- <div class="intro-message">
    <h1>Share City</h1>
    <h3></h3> -->
    <%#= link_to "Share on Facebook", "https://www.facebook.com/dialog/share?app_id=989408694457545&href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2F&redirect_uri=http://localhost:3000/", class: "btn btn-default btn-lg" %>
    <%#= link_to "Send a Dialog", "http://www.facebook.com/dialog/send?app_id=989408694457545&link=http://www.nytimes.com/interactive/2015/04/15/travel/europe-favorite-streets.html&redirect_uri=http://localhost:3000/", class: "btn btn-default btn-lg"%>
    <!-- https://www.facebook.com/dialog/share?app_id=989408694457545&display=popup&href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2F&redirect_uri=https%3A%2F%2Fdevelopers.facebook.com%2Ftools%2Fexplorer -->
    <!-- <a href="https://www.facebook.com/dialog/share?app_id=989408694457545&href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2F&redirect_uri=http://localhost:3000/" target="_blank">
      Share on Facebook
    </a> -->
    <!-- <div id="shareBtn" class="btn btn-primary btn-large input-suffix share-btn btn-facebook">Share On Facebook</div> -->


    <%#= link_to image_tag('/images/FaceBookIcon.png'), 'http://www.facebook.com/sharer.php?u='+request.fullpath, :target => :blank %>

    <!-- <hr class="intro-divider"> -->
    <!-- <ul class="list-inline intro-social-buttons">
        <li>
            <a href="https://twitter.com" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
        </li>
        <li>
            <a href="https://github.com/  " class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
        </li>
        <li>
            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
        </li>
    </ul> -->
<!-- </div> -->

<!-- <script>
document.getElementById('shareBtn').onclick = function() {
  FB.ui({
    display: 'popup',
    method: 'share',
    href: 'https://developers.facebook.com/docs/',
  }, function(response){});
}
</script> -->


<!-- <div id="friends">
  <p><%#= link_to "Invite your Facebook Friends", "#", :id => "invite_fb_friends" %></p>

  <div id="fb-root"></div>

  <script src= "http://connect.facebook.net/en_us/all.js"></script>

  <script>
    $(function(){

      $("a#invite_fb_friends").click(function(){
        FB.init({
        appId: '989408694457545',
        status: true,
        cookie: false,
        // xfbml: true
        });

      FB.ui({method: 'apprequests',

      });
    });
  </script>

  <#% end %>
</div> -->

app/views/home/pub.html.erb
<div class="stuff"></div>
<div class="chatboxinput">
  <form action="/msg" method="POST">
  <%#= form_for([@conversation, @message], url: {controller: 'home', action: 'msg'}, method: :post, :remote => true, :html => {id: "conversation_form_#{@conversation.id}"}) do |f| %>
    <textarea name="msg"></textarea>

    <div class="chat-form-btns">    
      <button>Send</button>
    </div>

  <%# end %>
  </form>

</div>

<script>
  jQuery(function($) {
    //if ($('.stuff').length > 0 ) {
    MessageBus.start();
    MessageBus.callbackInterval = 500;
    MessageBus.subscribe('/private/'+$('#current-user').attr('data-user_id'), function(data) {
      console.log(data); 
      var div = $('.stuff');
      $('<div>').text(data.msg + '- from ' + data.from).appendTo(div);
      $('textarea').val(''); 
    });
    //}
    $('form').on('submit', function(e) {
      e.preventDefault();
      var form = $(this);
      $.ajax('/msg', 
        { dataType: 'json',
          method: 'POST', 
          data: {msg: $('textarea').val(), rid: 8 },
          complete: function(xhr) {
            console.log(xhr.status);
            //MessageBus.publish('/private', function(data) { 
            //  console.log(data); 
            //}); 
          }
        }); 
    });
  });
</script>