config/routes.rb
Rails.application.routes.draw do

  get 'claims/index'

  get 'claims/new'

  # PRIVATE PUB TESTS
  get '/pub' => 'home#pub'
  post '/msg' => 'home#msg'

  get 'paypal_accounts/new'

  get 'paypal_accounts/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  match '/invites', to: 'invites#new', via: 'get'
  resources :invites, only: [:new, :create]

  resources :requested_items
  resources :billings
  # match '/billings/charge' => 'billings#charge', via: 'patch'
  put '/reservations/:id/updateWithPay' => 'reservations#updateWithPay'
  put '/reservations/:id/updateCheck' => 'reservations#updateCheck'
  put '/approveItem' => 'items#approveItem'

  get '/checkStripe' => 'items#check_stripe_connect'
  get '/charge' => 'billings#charge'
  get 'reviews/new'
  get 'reviews/show'
  get 'reviews/index'

  get 'dashboard/index'

  # post "emailapi/subscribe" => 'emailapi#subscribe'

  # get '/about' => 'pages#about'
  # get '/faq' => 'pages#faq'

  post '/rate' => 'rater#create', :as => 'rate'

  get '/conversations/:conversation_id/messages' => 'messages#show', as: :message
  post '/conversations/messages/new' => 'messages#new_message'
  post '/conversations/read' => 'conversations#read'

  post '/newclaim' => 'reservations#newclaim'

  resources :conversations, except: :show
  resources :activities
  # resources :profiles

  match "/contacts/:importer/callback" => "invites#new", :via => [:get]
  # google contacts callback
  match "/oauth2callback" => "main#contact", :via => [:get]
  # Yahoo contacts callback
  match "/callback" => "main#contact", :via => [:get]

  match "/send-invites" => "main#invite", :via => [:get]
  match "/import-emails" => 'invites#new', :via => [:get]

  match '/contacts', to: 'contacts#new', via: 'get'
  resources :contacts, only: [:new, :create]

  post '/items/share' => 'items#share'
  get '/items/item_preview/:id' => 'items#item_preview', as: :shareItem

  # get 'tags/index'
  resources :items do
    resources :reviews, only: [:create, :destroy]
  end
  resources :search_suggestions
  resources :password_resets,   only: [:new, :create, :edit, :update]
  resources :relationships,     only: [:create, :destroy]

  resources :item_attachments
  match '/item_attachments_delete' =>'item_attachments#destroy_img', :via => [:destroy]


  resources :items do
    resources :reservations, only: [:create, :update]
  end

  get '/preloadDates' => 'items#preloadDates'
  # get '/preload' => 'reservations#preload'

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'
  resources :reservations, only: [:index]

  resources :users, only: [:new, :create, :show] do
    collection do
      get   :edit
      patch :update
    end
    member do
      get :confirm_email
      get :following, :followers
    end
  end

  match '/auth/stripe_connect' =>'stripe_omniauth_callbacks#passthru', :via => [:get, :post]
  match '//auth/stripe_connect/callback' =>'stripe_omniauth_callbacks#stripe_connect', :via => [:get, :post]

  post '/users/create_email/' => 'users#create_email'
  get '/users/create_email/edit' => 'users#edit'
  patch '/users/create_email/' => 'users#update_email'
  patch '/users/code_update/' => 'users#code_update'
  put '/about_me_edit/' => 'users#update'
  # get 	'/message'  => 'users#message'
  # patch '/users/create_email' => 'users#create_email', :as => 'users/create_email'

  match '/tags/index' => 'tags#index', :via => :get
  # match '/tags/:id' => 'tags#show', :via => :get
  get 'tags/:tagname' => 'tags#tagged_items', as: :tagged_items
  get 'tags/:tag', to: "tags#index", as: "tag"

  match 'sessions/create_email' => 'sessions#create_email', :via => :post

  # match 'sessions/create_email' => 'sessions#create_email', :via => :post

  resources :sessions, only: [:new, :create, :destroy]
  get 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get 'auth/failure', to: 'sessions#failure', via: [:get, :post]
  # get 'auth/failure', to: redirect('/'), via: [:get, :post]
  get 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'pages#landing_main'
  get '/home' => 'home#index', as: "home", via: [:get]




  #api
  # namespace :api do
  #   namespace :v1 do
  #     resources :users, only: [:index, :create, :show, :update, :destroy]
  #     resources :items, only: [:index, :create, :show, :update, :destroy]
  #     # resources :sessions, only: [:create]
  #     match '/sessions' => 'sessions#create', :via => :get
  #
  #     get '/login' => 'users#login'
  #   end
  # end

  PagesController.action_methods.each do |action|
    get "/#{action}", to: "pages##{action}"
  end

end

app/models/requested_item.rb
class RequestedItem < ActiveRecord::Base
  belongs_to :user
  # validates :name, presence: true
end

app/controllers/requested_items_controller.rb
class RequestedItemsController < ApplicationController
  def new
    @requested_item = RequestedItem.new
  end
  def create
    @requested_item      = RequestedItem.new requested_params
    @requested_item.user = current_user
    if @requested_item.save
      redirect_to requested_items_path, notice: "The request has been posted!"
    else
      flash[:alert] = "An error occurred while creating this"
      render :new
    end
  end
  def index
    @requested_item = RequestedItem.new
    @requested_items = RequestedItem.all
  end
  def edit
    @requested_item = RequestedItem.find params[:id]
  end
  def update
    @requested_item = RequestedItem.find params[:id]
    if @requested_item.update requested_params
      redirect_to requested_items_path, notice: "Request Successfully updated!"
    else
      flash[:alert] = "See error(s) below..."
      render :edit
    end
  end
  def destroy
    @requested_item = RequestedItem.find params[:id]
    @requested_item.destroy
    redirect_to requested_items_path, notice: "Request Successfully deleted!"
  end
  private
  def requested_params
    params.require(:requested_item).permit(:name, :location, :user_id, :from_date, :to_date, :description)
  end
end

app/helpers/requested_items_helper.rb
module RequestedItemsHelper
end

app/views/requested_items/_edit.html.erb
<div class="row" id="ee">
  <%= form_for @requested_item do |request| %>
  <div class="col-xs-6">
    <%= request.label :name %>
    <%= request.text_field :name %>
  </div>
  <div class="col-xs-6">
    <%= request.label :location %>
    <%= request.text_field :location %>
  </div>
  <div class="col-xs-12">
    <br>
    <%= request.submit 'Edit', class: 'color-btn green-btn'%>
  </div>
<% end %>
</div>

app/views/requested_items/_followers.html.erb
<% @requested_items.each do |request| %>
<% if current_user.following?(request.user) %>
<div class="activity col-xs-12">
  <div class="row">
    <div style="padding-left: 8px;" class="col-xs-2">
      <img src="<%= request.user.image || request.user.avatar %>" alt="..." class="imgActi">
      <%=  %>
    </div>
    <div style="padding-left: 0;" class="col-xs-10">
      <div class="col-xs-12 col-sm-8">
        <h4 style="display: inline-block;font-size:15px;"><%= link_to request.user.full_name, user_path(request.user) %></h4>
        <h4 style="display: inline-block; color:#b9b9b9;font-size:15px;">requested a</h4>
        <h4 style="color: #337ab7;display: inline-block;font-size:15px;"><%= request.name.capitalize[0..6] %><br></h4>
      </div>
      <div style="text-align: right;padding-top: 11px;" class="hidden-xs col-sm-3">
        <%= (Date.current - request.created_at.to_date).to_i %>d ago
      </div>
    </div>
    <div style="padding-left: 0;" class="col-xs-10">
      <div class="col-xs-6">
        <i style="color: #6eb35a;" class="fa fa-map-marker" aria-hidden="true"></i> <%= request.location %>
      </div>
      <div style="text-align: center;" class="col-xs-6">
        <button type="button" class="btn btn-secondary detailBtn">Details</button>
        <% if request.user == current_user %>
        <div class="editBtnRequest">
          <%= link_to "Edit", edit_requested_item_path(request)%>
          <%#= link_to "Edit", "#editModal", "data-toggle": "modal"%>
          <%#= link_to "edit", edit_requested_item_path(request), class: "btn btn-mini", remote: true, "#editModal", "data-toggle": "modal" %>
          <!-- <a data-toggle="modal" data-target="#editModal" data-remote="<%= edit_requested_item_path(request) %> #ee">Edit</a> -->
        </div>
        <div class="deleteBtnRequest">
          <%= link_to "Delete", requested_item_path(request), method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>

        <!-- Modal -->
        <div id="editModal" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit a request</h4>
              </div>
              <div class="modal-body">
                <%= render 'edit' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>

        <% end %>
      </div>
    </div>
    <div class="col-xs-12 detailsCol">
      Start date: <%= request.from_date.strftime('%B %d, %Y') %>
      <br>
      End Date: <%= request.to_date.strftime('%B %d, %Y') %>
      <br>
      description: <%= request.description %>
    </div>
  </div>
</div>
<% end %>
<% end %>


<script type="text/javascript">
// $(document).ready(function() {
//   $(".detailBtn").click(function() {
//     if ($(this).text() == "Details") {
//       $('.detailsCol').show();
//       $(this).text("Close");
//     } else {
//       $('.detailsCol').hide();
//       $(this).text("Details");
//     }
//   });
// });
</script>

app/views/requested_items/_new.html.erb
  <div class="row">
    <%= form_for @requested_item do |request| %>
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-6">
          <%= request.text_field :name, label: false, placeholder: "Item Name" %>
        </div>
        <div class="col-xs-6">
          <%= request.text_field :location, label: false, placeholder: "Item location" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-6">
          <%= request.text_field :from_date, label: false, placeholder: "Start date" %>
        </div>
        <div class="col-xs-6">
          <%= request.text_field :to_date, label: false, placeholder: "end Date" %>
        </div>
      </div>
    </div>
    <div class="col-xs-12">
      <%= request.text_field :description, label: false, placeholder: "Description" %>
    </div>
    <div class="col-xs-12">
      <div class="row">
        <div class="col-xs-6">
          <%= request.submit 'submit', class: 'btn btn-primary', id: 'request-btn'%>
        </div>
        <div class="col-xs-6">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  <% end %>
  </div>

app/views/requested_items/_public.html.erb
<% @requested_items.each do |request| %>
<div class="activity col-xs-12">
  <div class="row">
    <div style="padding-left: 8px;" class="col-xs-2">
      <img src="<%= request.user.image || request.user.avatar %>" alt="..." class="imgActi">
    </div>
    <div style="padding-left: 0;" class="col-xs-10">
      <div class="col-xs-12 col-sm-8">
        <h4 style="display: inline-block;font-size:15px;"><%= link_to request.user.full_name.capitalize, user_path(request.user) %></h4>
        <h4 style="display: inline-block; color:#b9b9b9;font-size:15px;">requested a</h4>
        <h4 style="display: inline-block;font-size:15px;"><%= request.name.capitalize[0..6] %><br></h4>
      </div>
      <div style="text-align: right;padding-top: 11px;" class="hidden-xs col-sm-3">
        <%= (Date.current - request.created_at.to_date).to_i %>d ago
      </div>
    </div>
    <div style="padding-left: 0;" class="col-xs-10">
      <div class="col-xs-6">
        <i style="color: #6eb35a;" class="fa fa-map-marker" aria-hidden="true"></i> <%= request.location %>
      </div>
      <div style="text-align: center;" class="col-xs-6">
        <button type="button" class="btn btn-secondary detailBtn">Details</button>
        <% if request.user == current_user %>
        <div class="editBtnRequest">
          <%= link_to "Edit", edit_requested_item_path(request)%>
          <%#= link_to "Edit", "#editModal", "data-toggle": "modal"%>
          <%#= link_to "edit", edit_requested_item_path(request), class: "btn btn-mini", remote: true, "#editModal", "data-toggle": "modal" %>
          <!-- <a data-toggle="modal" data-target="#editModal" data-remote="<%= edit_requested_item_path(request) %> #ee">Edit</a> -->
        </div>
        <div class="deleteBtnRequest">
          <%= link_to "Delete", requested_item_path(request), method: :delete, data: { confirm: 'Are you sure?' }%>
        </div>

        <!-- Modal -->
        <div id="editModal" class="modal fade" role="dialog">
          <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Edit a request</h4>
              </div>
              <div class="modal-body">
                <%= render 'edit' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>

          </div>
        </div>

        <% end %>
      </div>
    </div>
    <!-- <div tyle="padding-left: 0;" class="col-xs-10">
    <%#= social_share_button_tag("Hey check out, im renting my #{request.name} on sharecity", :image => "http://localhost:3000/uploads/item_attachment/image/12/Cowboy_girl.jpg", desc: "The summary of page", via: "ShareCityhq") %>
    </div> -->
    <div class="col-xs-12 detailsCol">
      Start date: <%= request.from_date.strftime('%B %d, %Y') %>
      <br>
      End Date: <%= request.to_date.strftime('%B %d, %Y') %>
      <br>
      description: <%= request.description %>
    </div>
  </div>
</div>
<% end %>


<script type="text/javascript">
$(document).ready(function() {
  $(".detailBtn").click(function() {
    if ($(this).text() == "Details") {
      $('.detailsCol').show();
      $(this).text("Close")
    } else {
      $('.detailsCol').hide();
      $(this).text("Details")
    }
  });
});
</script>

app/views/requested_items/edit.html.erb
<%= render 'edit' %>

app/views/requested_items/index.html.erb
<section id="requested-items-section">
  <div class="wrapper-main">
    <div class="col-xs-12 col-sm-6">
      <h1 style="color: #5d5d5d; padding-left: 65px;">Items requested</h1>
    </div>
    <div class="col-xs-12 col-sm-6">
      <!-- Trigger the modal with a button -->
      <button type="button" class="btn reqItem" data-toggle="modal" data-target="#myModalRequest">Request an item now</button>
    </div>
    <br><br><br>
    <div style="margin-top: 40px;" class="col-xs-12">
      <div class="col-xs-6 col-sm-3 btnPub">
        <h3 class="h3PF active1">Community</h3>
      </div>
      <div class="col-xs-6 col-sm-3 btnFol">
        <h3 class="h3PF active2">Followers</h3>
      </div>
    </div>
    <div class="col-xs-12 col-sm-8" id="acti-main12">
      <div class="wrapperStream divPub">
        <% if @requested_items.length > 0 %>
          <%= render 'public' %>
        <% end %>
      </div>
      <div class="wrapperStream divFol">
        <% if @requested_items.length > 0 %>
          <%= render 'followers' %>
        <% end %>
      </div>
    </div>
    <div class="hidden-xs col-xs-4">
      <div class="theblogwidgets" style="">
        <div>
          <iframe src="http://www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Ffacebook.com%2Fsharecityhq&width=270&colorscheme=light&show_faces=true&border_color=white&connections=9&stream=false&header=false&height=270" scrolling="no" frameborder="0" scrolling="no" style="border: white; overflow: hidden; height: 270px;color:000;"></iframe>
        </div>
      </div>
    </div>
    <div class="hidden-xs col-xs-4">
      <a class="twitter-timeline" data-height="317" data-theme="dark" data-link-color="#4692b4" href="https://twitter.com/ShareCityHQ">Tweets by ShareCityHQ</a>
      <!-- <a class="twitter-timeline" href="https://twitter.com/ShareCityHQ">Tweets by ShareCityHQ</a> -->
    </div>
  </div>
  <!-- Modal -->
  <div id="myModalRequest" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Request a new item</h4>
        </div>
        <div class="modal-body">
          <%= render 'new' %>
        </div>
      </div>

    </div>
  </div>
</section>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<script type="text/javascript">
  $('.btnFol').on('click', function() {
    $('.divPub').hide();
    $('.divFol').show();
    $('.active2').css('color', '#337ab7');
    $('.active1').css('color', '#bababa');
  });
  $('.btnPub').on('click', function() {
    $('.divFol').hide();
    $('.divPub').show();
    $('.active1').css('color', '#337ab7');
    $('.active2').css('color', '#bababa');
  });
</script>

app/views/requested_items/new.html.erb
<%= render 'new' %>